#server
server:  port: 80
  tomcat:    uri-encoding: utf-8
    max-threads: 1000
    min-spare-threads: 100
  servlet:    context-path: /

#spring
spring:  datasource:    url: jdbc:mysql:///jtsys?serverTimezone=GMT%2B8&characterEncoding=UTF8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/    cache: false
  aop:    proxy-target-class: false  #JDK
  task:    execution:      pool:        core-size: 50
        max-size: 100
        queue-capacity: 200
        keep-alive: 60
        allow-core-thread-timeout: false
      thread-name-prefix: db.spring.thread.task-
#mybatis    
mybatis:  configuration:    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:  - classpath:/mapper/*/*.xml
  
#logging
logging:  level:   com.cy: debug
  file: D:/TCGBIII/a.log
#page
page.config: 
    pageSize: 5 
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
    
    
    
  
    
    